# Header
menu:
  Portfolio: /portfolio
  Blog: /blog
  About: /about
rss: /atom.xml

# Content
excerpt_link: More
fancybox: false

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# Miscellaneous
google_analytics: UA-51335839-1
favicon: /images/favicon.ico
twitter: joshuarrrr
google_plus:
fb_admins:
fb_app_id: